### ISSUE TITLE
Dealing with missing values

### ISSUE THREAD

**Issue by gheger11** [ahmohamed/lipidr#11]
Hi,
Does this package deal with missing values in lipidomics data? They are often due to quantity of a lipid below the detection limit of the device, and are therefore informative. I'm trying to figure out the best way of imputing them. I think this would be a nice feature of a package for lipidomics analysis.
Thanks!

**Comment by ahmohamed** [comment]
Thanks @gheager 
The current implementation automatically replaces `NA`s with minimum detected value in the dataset (with a warning to indicate that). This assumes that missingness is due to low abundance (the molecule is below the detection limit). 

Other imputations can be readily applied using functions from [imputeLCMD](https://www.rdocumentation.org/packages/imputeLCMD/versions/2.0) package. Since all these methods take numerical matrix as input, you can easily integrate with `lipidr` using `assay` method.

```r
library(lipidr)
library(imputeLCMD)
data("data_normalized")
assay(data_normalized, "Area") <- impute.QRILC(assay(data_normalized, "Area"))
```

I'll think about including a wrapper function for imputation in `lipidr` since it seems it's a popular request.

**Comment by ahmohamed** [comment]
Imputation has been included in `lipidr`. Please refer to https://www.lipidr.org/reference/impute_na.html for usage and examples.
