### ISSUE TITLE
Showing plot_chain_distribution(data) for multiple groups at the same time

### ISSUE THREAD

**Issue by FernandoTobias** [ahmohamed/lipidr#19]
Hello-
In the vignettes, it has been shown being able to show multiple volcano plots at the same time from 2 or more groups. Is it possible to show for plot_chain_distribution(data) with 2 or more groups? While Log2FC scaling remains the same across the groups? 

I have done separate plot_chain_distribution(data) for a 3 groups of my data but am having trouble with showing them at the same color scaling. Thank you.

**Comment by ahmohamed** [comment]
Hi Fernando,
Unfortunately, `plot_chain_distribution` cannot display multiple comparisons at the same time, mainly because of `ggplot2` limitations. `facet_wrap` that is used to display multiple groups in other functions is already used to display classes.

However, you can definitely have multiple plots on the same color scale. Basically, all `lipidr` plot functions return a `ggplot` object that you can hack / modify as needed. In this case you can override the color scale with your own:

`plot_chain_distribution(de_results) + ggplot2::scale_fill_gradient2(midpoint = 0, limits=c(-3, 3))`

Let me know if that addresses the issue.

**Comment by FernandoTobias** [comment]
That's a shame, but yes your suggestion helps!

Thanks - this addresses my issue.
